config/routes.rb
Rails.application.routes.draw do

  get 'home/index' => 'home#index'
  get 'search' => 'home#search'
  get 'analyze' => 'home#analyze'

  get '/log-in' => 'sessions#new'
  post '/log-in' => 'sessions#create'
  get 'log-out' => 'sessions#destroy'
  
  root 'home#index'

  resources :twittersearches
  resources :textsearches
  resources :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>All-Seeing Eye</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Karla:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
</head>
<body>
	<nav id="navbar">
		<span id= 'logo'>
			<!-- for refactoring: switch these links to root path -->
			<a href="/home/index.html"><img src='/assets/eyelogo.png'></a> <br>
		 	<a href="/home/index.html">we know what you <i>really</i> think.</a>
		 </span>
		 <% if !current_user %> 
		<ul>
			<li><%= link_to "about", "#", :class => "modal-link link"%></li>					
			<li><%= link_to "sign up", new_user_path, :class => "link" %></li>
			<li><%= link_to "log in", log_in_path, :class => "link" %></li>
		</ul>
		<% else %>
		<ul>
			<li><%= link_to "about", "#", :class => "modal-link link"%></li>					
			<li><%= link_to "account", user_path(@user), :class => "link" %></li>
			<li><%= link_to "log out", log_out_path, :class => "link" %></li>
		</ul>
		<% end %>
	</nav>

	<div id='paddingdiv'></div>

<% if @user %>
	<div id='sidebar'>
		<% @recenttwittersearches = @user.twittersearches.last(5) %>
		<% @recenttextsearches = @user.textsearches.last(5) %>
		<ul><h4>Your Last 5 Twitter Searches:</h4>
			<% @recenttwittersearches.each do |n| %>
				<li><%= link_to "@#{n.tweeter}", twittersearch_path(n.id)%><%=" -  #{time_ago_in_words(n.created_at)} ago" %></li>
			<% end %>
		</ul>
		<ul> <h4>Your Last 5 Text Searches:</h4>
			<% @recenttextsearches.each do |n| %>
				<li><%=  link_to "#{n.title}", textsearch_path(n.id) %><%=" -  #{time_ago_in_words(n.created_at)} ago" %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%= yield %>

<script src="//d3js.org/d3.v3.min.js" charset="utf-8"></script>
</body>
</html>